# Generated by Django 5.1.4 on 2025-01-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.CharField(max_length=10)),
                ('image_url', models.TextField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
